apiVersion: v1
kind: Service
metadata:
  name: celebrity-booking-api-service
  namespace: production
  labels:
    app: celebrity-booking-api
    environment: production
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /health
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "3000"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3000
    protocol: TCP
  selector:
    app: celebrity-booking-api
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: celebrity-booking-api-internal
  namespace: production
  labels:
    app: celebrity-booking-api
    environment: production
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: celebrity-booking-api